### ISSUE TITLE
Cannot collect data when Apache is running in a different port

### ISSUE THREAD

**Issue by andbuitra** [Lusitaniae/apache_exporter#105]
When running NGINX as a proxy for Apache, NGINX will take the default ports. If you choose to keep scraping from the normal endpoint data may be stale due to caching or may result in different issues (at least in my setup) like: `apache_exporter[643684]: 2021/06/22 08:49:29 http: Accept error: accept tcp [::]:9117: accept4: too many open files; retrying in 1s`.

scrape_uri cannot be used to collect from a different port (like 81) because it complains: `first path segment in URL cannot contain colon`

**Comment by Lusitaniae** [comment]
hi @andbuitra 

You could have nginx proxy requests (withotu cache) to Apache no?

**Comment by andbuitra** [comment]
@Lusitaniae I just checked and it actually is not caching the server-status but the exporter is not collecting the data. When restarted it collects it and after a random amount of time it stops. Before it used to show the "too many open files" but I increased the openfile limit in the systemd unit. Now it just doesn't do it. 

I've enabled debug mode and upgraded to 0.9.0 from 0.8.0 just to check. I'll see how long it lasts

**Comment by Lusitaniae** [comment]
Worth looking specifically into what process is keeping too many open files.

See https://serverfault.com/questions/707490/how-to-determine-which-processes-have-most-inodes-opened

I would not expect apache exporter or nginx to cause that. 

Do you also have application server running in the same server? Or is Apache creating too many processes?

**Comment by Lusitaniae** [comment]
For troubleshooting, usually you run the exporter manually

Either stop the systemd script or run the exporter on a different port.

`./apache_exporter --telemetry.address=":9999"`

For changes, see

https://github.com/Lusitaniae/apache_exporter/commit/0115c2dec8617b8c2e7273f1c1ba67d6b13496ae

Drop vendor dir, update modules
https://github.com/Lusitaniae/apache_exporter/commit/9d3ba3e741c34f7a59f2744ce2af0186515722a0

The CI/CD changes also upgraded Go

**Comment by andbuitra** [comment]
The unit stopped shortly after you replied, unfortunately :/

I will run the exporter manually on a screen and see how it goes

**Comment by andbuitra** [comment]
```
127.0.0.1 - - [23/Jun/2021:14:12:21 -0500] " GET /server-status/?auto HTTP/1.1 " 200 1415 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [23/Jun/2021:14:12:31 -0500] " GET /server-status/?auto HTTP/1.1 " 200 1415 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [23/Jun/2021:14:12:41 -0500] " GET /server-status/?auto HTTP/1.1 " 200 1416 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [23/Jun/2021:14:12:51 -0500] " GET /server-status/?auto HTTP/1.1 " 200 1416 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [23/Jun/2021:14:13:01 -0500] " GET /server-status/?auto HTTP/1.1 " 200 1412 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [23/Jun/2021:14:13:11 -0500] " GET /server-status/?auto HTTP/1.1 " 200 1417 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [23/Jun/2021:14:16:21 -0500] " GET /server-status?auto HTTP/1.1 " 200 1417 "-" "curl/7.29.0" "-"
```

After that nothing is requested. The exporter is still running on the screen:

```
INFO[0000] Starting apache_exporter (version=0.9.0, branch=HEAD, revision=5f55c8eafd0c5e51237736b361db395b2b2b5e09)  source="apache_exporter.go:367"
INFO[0000] Build context (go=go1.16.5, user=root@8855f7ef9546, date=20210606-11:51:22)  source="apache_exporter.go:368"
INFO[0000] Starting Server: :9117                        source="apache_exporter.go:369"
INFO[0000] Collect from: http://localhost/server-status/?auto  source="apache_exporter.go:370"
INFO[0000] listening and wait for graceful stop          source="apache_exporter.go:374"
```

**Comment by Lusitaniae** [comment]
@andbuitra Have you found a solution?

I will close the issue for now, feel free to update if you need
