### ISSUE TITLE
Docker Build Error [FIX]

### ISSUE THREAD

**Issue by PraveenAlexis** [Lusitaniae/apache_exporter#106]
Dear Team,

in teh docker file it says ".build/${OS}-${ARCH}/apache_exporter" this gives and error if you make using go the "apache_exporter" file actually will be in "./apache_exporter"

so in the dockerfile it should be "COPY ./apache_exporter /bin/apache_exporter"

Thank You!

**Comment by Lusitaniae** [comment]
hi @PraveenAlexis 

The docker image is used by the CI/CD to release new artifacts (using promu instead of Make). 

Is not meant for end users.
