### ISSUE TITLE
https scraping

### ISSUE THREAD

**Issue by donjuanmon** [Lusitaniae/apache_exporter#108]
Hello,

Is it possible to scrape apache_exporter data over https? Similar to how node_exporter uses 

```
tls_server_config:
  cert_file: node_exporter.crt
  key_file: node_exporter.key
```
with the --web.config flag?

**Comment by Lusitaniae** [comment]
That looks like a new feature backed by a WIP/experimental module https://github.com/prometheus/exporter-toolkit/tree/v0.1.0

It's not currently supported, feel free to submit a PR

**Comment by donjuanmon** [comment]
Sounds good, we can close this for now.
