### ISSUE TITLE
mod_proxy metrics report stale / old data for backend status

### ISSUE THREAD

**Issue by frittentheke** [Lusitaniae/apache_exporter#109]
Thanks @rainerjung for implementing mod_proxy metrics (https://github.com/Lusitaniae/apache_exporter/pull/102) - greatly appreciated.

1. 

I just updated to the new apache_exporter release (https://github.com/Lusitaniae/apache_exporter/releases/tag/v0.10.0). It works great, but unfortunately I ran into a bug with stale data on the reported state of balancer members ....

Initially the status for all backends is reported correctly, i.e.
```
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-01.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-02.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-03.example.com:7481"} 1
```

When the status changes though, the old status continues to be exported as well:
```
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Dis",worker="http://host-01.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Dis",worker="http://host-02.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Dis",worker="http://host-03.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-01.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-02.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-03.example.com:7481"} 1

```
I believe this is due to the currently reported status from the scoreboard is simply being added to exported data, but none of the old, non-current status data is ever removed in https://github.com/Lusitaniae/apache_exporter/pull/102/files#diff-fb1d52e526ddf3b580f7d8c5378ed5b4154d782c9de8da9e517b43ddf3d970fcR512

2. 

If I may raise another idea in this regard. Currently only the actual status string reported in the scoreboard is reported with value "1", but none of the others with value "0". The various status values are documented (https://httpd.apache.org/docs/trunk/howto/reverse_proxy.html#status) and looking at i.e. the node_exporter (https://www.robustperception.io/linux-software-raid-metrics-from-the-node-exporter) which reports state in this manner for i.e. `node_systemd_unit_state` or `node_md_stat`

```
node_md_state{device="md0",state="active"} 1
node_md_state{device="md0",state="inactive"} 0
node_md_state{device="md0",state="recovering"} 0
node_md_state{device="md0",state="resync"} 0
```

I know this creates more time series, but it does not waste storage with values rarely changing and it would simply aligns things style-wise.

**Comment by rainerjung** [comment]
Thank you for giving the details. I will look into it, but a friendly ping will help me not forgetting about it.

**Comment by frittentheke** [comment]
@rainerjung  ... may I kindly remind you again ;-)

**Comment by frittentheke** [comment]
@rainerjung  @Lusitaniae  ... I pushed a small PR just adding a reset to the ProxyBalancer metrics on each scrape.
Do you guys mind having a look if this works and fixes the issue of stale metrics?
