### ISSUE TITLE
Add ability to allow or disable specific metrics

### ISSUE THREAD

**Issue by blkperl** [Lusitaniae/apache_exporter#110]
Would there be any interest in new configuration that allows the users to choose which metrics are sent by the exporter? I can submit a pull request.

In my use case we have thousands of pods running apache and we have exceeded our quota for metrics so we want to restrict the metrics sent to the ones that are needed.

**Comment by roidelapluie** [comment]
The Apache exporter is straightforward. We do not really have any metrics that makes more sense than others.

My suggestion is that you should use Prometheus relabeling to keep the metrics you are interested in.

**Comment by blkperl** [comment]
Thanks for the information! I found some filtering examples online.

**Comment by Lusitaniae** [comment]
Feel free to submit a PR with some changes to the README with some examples, in case it's useful to someone else too :)
