### ISSUE TITLE
rename the outputs while displaying in webapp

### ISSUE THREAD

**Issue by jijojohn1985** [Lusitaniae/apache_exporter#117]
Hi @Lusitaniae ,

I m trying to send the data for workers to cloudwatch , but cloudwatch is not detecting the metrics in console since the name has special characters in it. Can we rename the below to some thing like **apache_workers_state_busy**  & **apache_workers_state_idle** while displaying in webapp (http://localhost:9117/metrics

other metrics i am able to pull and show in cloudwatch like **apache_accesses_total, apache_cpuload,apache_up**

apache_workers{state="busy"} 1
apache_workers{state="idle"} 6

Please help if there are any options for this.

Thanks,
Jijo John

**Comment by Lusitaniae** [comment]
You could use Cloudwatch agent to pull Apache Metrics?
