### ISSUE TITLE
scrape multiple vhost domains from same server

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [Lusitaniae/apache_exporter#118]
I have a server that hosts 3 websites(virtual hosts). And I have deployed an apache exporter on this server. Now in the scrape_uri how can I add all there domain names?

Also I would like to use `--host_override`

**Comment by Lusitaniae** [comment]
You don’t have to.

There’s only one instance of Apache running on your server, you only need
to read the metrics from one host name, if I understand correctly.

**Comment by BhuviTheDataGuy** [comment]
oh ok, may be I didnt understand the concept of the server status.

If I use this config, then will the exporter capture all the metrics?

```
<Location "/server-status">
    SetHandler server-status
    Require host example1.com example2.com example3.com
</Location>
```

**Comment by Lusitaniae** [comment]
Location block is inside server block

If you server block is serving requests for  example1.com then "Request
host  example1.com" is enough

This is just a safety measure, which means only example1.com will serve
/server-status requests.

Apache metrics are "global", so all those hosts report the same metrics.
