### ISSUE TITLE
Running as systemctl with host override not working 

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [Lusitaniae/apache_exporter#119]
I have a systemctl file to call the apache exporter and it was working fine.

apache_exporter —scrape_uri=“http://localhost/server-status?auto”

But by using this, i was not getting most of the  metrics(tried to get the metrics via curl localhost:9117/metrics | grep apache), then I manually ran the command along with —host_override=mdomain.com

then im getting All the metrics, when i put this flag in systemctl file, the service is not running, unfortunately my linux server is not producing any logs in syslog file.

Note: i have enables the server status inside the virtual host block.

**Comment by Lusitaniae** [comment]
is this still an issue?

You may consider posting these type of questions on StackOverflow, since it's more about your special setup than the exporter itself, and you could get support from more people quicker

**Comment by BhuviTheDataGuy** [comment]
Sure, we can close this.
