### ISSUE TITLE
Error when retrieving the version number

### ISSUE THREAD

**Issue by zebby76** [Lusitaniae/apache_exporter#123]
We get an error when retrieving the version number with parameter ```--version``` .

> docker run -it --rm docker.io/lusotycoon/apache-exporter:v0.11.0 --version
> apache_exporter: error: unknown long flag '--version', try --help

Any suggestions ?

Thanks.
Seb.

**Comment by Lusitaniae** [comment]
Seems to be a  regression from the last release

Would you like to look into it and submit a PR ?

**Comment by tboerger** [comment]
Maybe you could release a version including that fix?
