### ISSUE TITLE
apahce_up gauge showing 0 even though the apache_exporter is running

### ISSUE THREAD

**Issue by allwithjava** [Lusitaniae/apache_exporter#134]
We have installed apache_exporter in both test server and prod server and exporting the metrics to prometheus. The thing is all the configuration files looks similar wrt apache, and apache_exporter, but couldn't figure out where the problem is. when i check the status of apache_exporter in TEST, this is what i see....

May 16 15:31:58 proxy-server-test.com apache_exporter[6687]: time="2022-05-16T15:31:58+02:00" level=error msg="Error scraping apache: error scraping apache: Get http://localhost/server-status/?auto: dial tcp 127.0.0.1:80: connect: connection refused" source="apache_exporter.go:335"
May 16 15:32:13 proxy-server-test.com apache_exporter[6687]: time="2022-05-16T15:32:13+02:00" level=error msg="Error scraping apache: error scraping apache: Get http://localhost/server-status/?auto: dial tcp 127.0.0.1:80: connect: connection refused" source="apache_exporter.go:335"
May 16 15:32:28 proxy-server-test.com apache_exporter[6687]: time="2022-05-16T15:32:28+02:00" level=error msg="Error scraping apache: error scraping apache: Get http://localhost/server-status/?auto: dial tcp 127.0.0.1:80: connect: connection refused" source="apache_exporter.go:335"

**Comment by Lusitaniae** [comment]
hi @allwithjava please see the FAQ

https://github.com/Lusitaniae/apache_exporter#faq

"Q. Its not working! Apache_up shows as 0"
