### ISSUE TITLE
Is v0.12.0 ready for use?

### ISSUE THREAD

**Issue by blkperl** [Lusitaniae/apache_exporter#146]
Hey @Lusitaniae, I see that [v0.12.0](https://github.com/Lusitaniae/apache_exporter/releases/tag/v0.12.0) was tagged in Jan but is still marked pre-release. Is that an oversight or is it not ready for use?

I would love to see #143 included in a release as well. I can open a PR for golang 1.20 as well if you are interested

**Comment by Lusitaniae** [comment]
I was having issues with the CI/CD build last time so I didn't mark it as ready

Yes, please do make a PR

**Comment by Lusitaniae** [comment]
Seeing that other exporters are now moving to GH actions I started a PR moving in that direction too

Including upgrade to go 1.19 and other lib upgrades 

https://github.com/Lusitaniae/apache_exporter/pull/147

still getting some errors so if you have ideas on how to address these please let me know!

**Comment by blkperl** [comment]
@Lusitaniae Looks like the issue is prometheus-common https://github.com/prometheus/common/blob/main/go.mod#L16 is using the old version which probably conflicts with the new version.

```
go mod why -m gopkg.in/alecthomas/kingpin.v2
# gopkg.in/alecthomas/kingpin.v2
github.com/Lusitaniae/apache_exporter
github.com/prometheus/common/promlog/flag
gopkg.in/alecthomas/kingpin.v2
```
