### ISSUE TITLE
When is Next release 0.13.0 planned?

### ISSUE THREAD

**Issue by pradeepkarnam** [Lusitaniae/apache_exporter#156]
Hello,

I see 0.13.0 is a Pre-release build. By when can we expect 0.13.0 as a release?

**Comment by Lusitaniae** [comment]
just made new release 0.13.1

If you'd like to test I'll remove the "pre-release" flag

**Comment by pradeepkarnam** [comment]
Please go ahead and remove "Pre-release" flag

**Comment by Lusitaniae** [comment]
done

thanks for your feedback
