### ISSUE TITLE
Unexpected metrics 

### ISSUE THREAD

**Issue by dmclark** [Lusitaniae/apache_exporter#169]
I added comment to #116 and I realized that it should be a new issue.

Is it because I'm

    wget https://github.com/Lusitaniae/apache_exporter/releases/download/v1.0.1/apache_exporter-1.0.1.linux-amd64.tar.gz
    tar xvfz apache_exporter-1.0.1.linux-amd64.tar.gz
    cp apache_exporter-1.0.1.linux-amd64/apache_exporter /usr/local/bin/

Rather than building 

The output is 

`
# HELP apache_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, goversion from which apache_exporter was built, and the goos and goarch for the build.
# TYPE apache_exporter_build_info gauge
apache_exporter_build_info{branch="HEAD",goarch="amd64",goos="linux",goversion="go1.19.11",revision="92eeaa4d50aea1ba26b0392534a7b33fd19c9002",tags="netgo",version="1.0.1"} 1
# HELP apache_exporter_scrape_failures_total Number of errors while scraping apache.
# TYPE apache_exporter_scrape_failures_total counter
apache_exporter_scrape_failures_total 1303
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 6.6859e-05
go_gc_duration_seconds{quantile="0.25"} 0.000177412
go_gc_duration_seconds{quantile="0.5"} 0.000275214
go_gc_duration_seconds{quantile="0.75"} 0.000439931
go_gc_duration_seconds{quantile="1"} 0.010819656
go_gc_duration_seconds_sum 0.098762856
go_gc_duration_seconds_count 145
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 12
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.19.11"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 5.784288e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 3.38701712e+08
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4622
...................
`

**Comment by Lusitaniae** [comment]
Looks like cannot connect to Apache, hence

`apache_exporter_scrape_failures_total 1303`

Did you look at the README there's some details about what needs to be setup

**Comment by blkperl** [comment]
Let us know if you need any additional help!
