### ISSUE TITLE
Filtering apache_accesses_total by url

### ISSUE THREAD

**Issue by mathiasHillmann** [Lusitaniae/apache_exporter#170]
Is it possible to filter the metric `apache_accesses_total` by the url? 

As in get all accesses on routes that start with `/api` and all accesses on routes that start with `/web`, like:

```
/api/users
/api/system
/web/chart1
/web/chart2
```

**Comment by blkperl** [comment]
Hey @mathiasHillmann,

I don't believe it's possible but you could get a similar result by parsing the logs in a log aggregator and then graphing the result.
