### ISSUE TITLE
-version flag

### ISSUE THREAD

**Issue by joker234** [Lusitaniae/apache_exporter#18]
please include a `-version` flag. It will be useful for all administrators of production systems and for debugging purposes.

**Comment by waqark3389** [comment]
+1

**Comment by salihoglu87** [comment]
Hello! I tried to build a docker image from your Dockerfile and your ".go" scripts. I suceeded to build a ".go" binary and also to build an Docker Image. But if i try to run it a container it always fails with a message: "docker: Error response from daemon: Container command '/apache_exporter' not found or does not exist".

**Comment by Lusitaniae** [comment]
Solved on #26.
