### ISSUE TITLE
assets missing for V1.04

### ISSUE THREAD

**Issue by corporate-gadfly** [Lusitaniae/apache_exporter#181]
Only source code is available. Binaries are missing.

**Comment by Lusitaniae** [comment]
Thanks for the report! We'll try to get it fixed soon

**Comment by viscountstyx** [comment]
Serves me right for pulling the amd64 release in scripts :)

As it's been a few weeks - any chance of these being created?

Thanks in Advance :)

**Comment by Lusitaniae** [comment]
v1.0.5 to the rescue!

https://github.com/Lusitaniae/apache_exporter/releases/tag/untagged-f92d8c6e05511ec0558d

how does that work fro you

**Comment by viscountstyx** [comment]
> v1.0.5 to the rescue!
> 
> https://github.com/Lusitaniae/apache_exporter/releases/tag/untagged-f92d8c6e05511ec0558d
> 
> how does that work for you

404 I'm afraid!

I can see the pre-release but https://github.com/Lusitaniae/apache_exporter/releases/download/v1.05/apache_exporter-1.05.linux-amd64.tar.gz seems to be a no

**Comment by viscountstyx** [comment]
Also - I spotted the naming convention change from v1.0.X to v1.0X which I've had to adjust in my curls, just in case anyone else misses that ha!

**Comment by blkperl** [comment]
Oh my bad, https://github.com/Lusitaniae/apache_exporter/releases/tag/v1.04 has a typo. It should have been v1.0.4

**Comment by blkperl** [comment]
@viscountstyx https://github.com/Lusitaniae/apache_exporter/releases/download/v1.05/apache_exporter-1.0.5.linux-amd64.tar.gz works as expected now. Sorry for the trouble!

**Comment by viscountstyx** [comment]
Thanks @blkperl , just going to be that guy to point out that the archive name is 1.0.5 but the folder structure is 1.05 ha

**Comment by Lusitaniae** [comment]
where?
https://github.com/Lusitaniae/apache_exporter/releases/tag/v1.0.5

![image](https://github.com/Lusitaniae/apache_exporter/assets/58325/217f7cac-491b-42b4-b3ce-ac2b8822ae33)

**Comment by viscountstyx** [comment]
Ah, apologies - The link given above for https://github.com/Lusitaniae/apache_exporter/releases/download/v1.05/apache_exporter-1.0.5.linux-amd64.tar.gz contains v1.05 in the path - but that 404's, which it should :)

https://github.com/Lusitaniae/apache_exporter/releases/download/v1.0.5/apache_exporter-1.0.5.linux-amd64.tar.gz
works :)

As you were!

**Comment by dswarbrick** [comment]
@blkperl Is there any chance you could remove the erroneous v1.04 and v1.05 tags? They cause issues with automated upstream version monitoring, such as that used by Debian "watch" files in packaging, since v1.05 is considered newer than v1.0.6 (semantic versioning).

**Comment by blkperl** [comment]
Yep, deleted them.
