### ISSUE TITLE
Set User-Agent to something more meaningful

### ISSUE THREAD

**Issue by theS1LV3R** [Lusitaniae/apache_exporter#185]
At the moment Apache exporter uses the default Go HTTP User-Agent (`Go-http-client/1.1`), spamming HTTP request logs with the following:

```
::1 - - [03/Jan/2024:09:44:01 +0100] "GET /server-status?auto HTTP/1.1" 403 6865 "-" "Go-http-client/1.1"
::1 - - [03/Jan/2024:09:45:31 +0100] "GET /server-status?auto HTTP/1.1" 403 6865 "-" "Go-http-client/1.1"
::1 - - [03/Jan/2024:09:47:01 +0100] "GET /server-status?auto HTTP/1.1" 403 6865 "-" "Go-http-client/1.1"
::1 - - [03/Jan/2024:09:48:31 +0100] "GET /server-status?auto HTTP/1.1" 403 6865 "-" "Go-http-client/1.1"
::1 - - [03/Jan/2024:09:50:01 +0100] "GET /server-status?auto HTTP/1.1" 403 6865 "-" "Go-http-client/1.1"
```

Is it possible to change the User-Agent that is used, [like Prometheus did a while ago](https://github.com/prometheus/prometheus/issues/2440)? I suggest using something like `Apache-Exporter/<version>`, in the same way they did: https://github.com/prometheus/prometheus/pull/2447/files

**Comment by blkperl** [comment]
@theS1LV3R sounds good to me, would you like to submit a PR?

**Comment by blkperl** [comment]
Thanks @theS1LV3R for the contribution!
