### ISSUE TITLE
Update Go dependancies for fix a CVE

### ISSUE THREAD

**Issue by AureProd** [Lusitaniae/apache_exporter#204]
Hello I use your exporter in a docker image of one of my projects but do you have a solution for me to update the **Go** dependencies of your project because **Trivy** a tool which analyzes security vulnerabilities in docker containers finds a CVE on a version of the **Go** dependency that you are using (do you have a way that I can update or rebuild your tool by updating the **Go** libraries without you having to do a release)

The **Trivy** result :
![image](https://github.com/Lusitaniae/apache_exporter/assets/71317162/a3f4f67c-0e76-4cc1-93d7-5ebe5028fd01)

My **dockerfile** implementation of your tool : 
![image](https://github.com/Lusitaniae/apache_exporter/assets/71317162/81252e8e-a8c2-4477-ab25-403b86bad6d5)

**Comment by Lusitaniae** [comment]
fastest option would be you make your own build with updated dependencies

but if it's a security vulnerability affecting current releases then a PR would be most welcome :)

**Comment by AureProd** [comment]
ok no problem,

After a test to build your tool, I have 2 problems : 

These problems there are not important but you can update the doc in readme

- for build with make
  ```bash
  docker run --rm -v .:/usr/local/go/src/github.com/Lusitaniae/apache_exporter -w /usr/local/go/src/github.com/Lusitaniae/apache_exporter golang:latest make
  ```
  I have this error : 

  ![image](https://github.com/Lusitaniae/apache_exporter/assets/71317162/854d4bd7-dfce-4262-8c09-4dfa9823f732)
  
- for build with docker : 
  ```bash
  docker build -t apache_exporter .
  ```
  
  this build is not possible because in the dockerfile contains this : 
  
  ![image](https://github.com/Lusitaniae/apache_exporter/assets/71317162/be1f5e1f-175d-475a-ae4e-0b7e3f561357)

  and in local repo there are no folder .build

My solution for build in local repo is : 

```bash
# for get and update go dependancies
docker run --rm -v .:/usr/local/go/src/github.com/Lusitaniae/apache_exporter -w /usr/local/go/src/github.com/Lusitaniae/apache_exporter golang:latest go get

# for build apache_exporter
docker run --rm -v .:/usr/local/go/src/github.com/Lusitaniae/apache_exporter -w /usr/local/go/src/github.com/Lusitaniae/apache_exporter golang:latest go build -buildvcs=false
```

**Comment by AureProd** [comment]
tell me if you want a PR for the version and the doc ;)

**Comment by blkperl** [comment]
Looks like the dependabot pr is closed so I'm closing this out. Thanks!
