### ISSUE TITLE
Problem with go get github.com/neezgee/apache_exporter

### ISSUE THREAD

**Issue by petarkozic** [Lusitaniae/apache_exporter#22]
Centos 6.7
go version go1.8.3 linux/amd64

I installed several exporter without problems !

When type
go get github.com/neezgee/apache_exporter
nothing happend !!
Some help ?

**Comment by neezgee** [comment]
Just checked if I can build it on ubuntu. `go get github.com/neezgee/apache_exporter` worked for me without any problem. Sorry, I don't have centos installation available to check it there.

Looks like it's a problem with your go environment. Can you install other packages with `go get`?

**Comment by petarkozic** [comment]
Yes,
I’m installed about 5 exporter yesterday with go get, but this apache
exporter I can’t !



On August 1, 2017 at 3:07:57 PM, neezgee (notifications@github.com) wrote:

Just checked if I can build it on ubuntu. go get
github.com/neezgee/apache_exporter worked for me without any problem.
Sorry, I don't have centos installation available to check it there.

Looks like it's a problem with your go environment. Can you install other
packages with go get?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/neezgee/apache_exporter/issues/22#issuecomment-319364656>,
or mute the thread

**Comment by ptrourke** [comment]
I'm seeing a similar problem on RedHat 6.9; it seems like it is hanging on retrieving AlecThomas's  kingpin.v2 gopkg.in package, so it might be a dependency issue.

**Comment by ganeshkaila** [comment]
`go get github.com/neezgee/apache_exporter` isn't going well in Ubuntu 16.04 and CentOS 7 for me. I have tried the same in Ubuntu 14.04, it worked.!

**Comment by petarkozic** [comment]
Can you describe your problem with apache_exporter ?


On October 31, 2017 at 10:12:06 AM, Ganesh Kaila (notifications@github.com)
wrote:

go get github.com/neezgee/apache_exporter isn't going well in Ubuntu 16.04
and CentOS 7 for me. I have tried the same in Ubuntu 14.04, it worked.!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lusitaniae/apache_exporter/issues/22#issuecomment-340702663>,
or mute the thread

**Comment by ganeshkaila** [comment]
I am seeing the following errors in my environment. My apologies, I have seen this error another machine which has Ubuntu 14.04, not Ubuntu 16.04.
```
biarca@prometheus-yes:~$ go version
go version go1.2.1 linux/amd64
biarca@prometheus-yes:~$ echo $GOPATH
/home/biarca/go
biarca@prometheus-yes:~$ go get github.com/neezgee/apache_exporter
# golang.org/x/sys/unix
go/src/golang.org/x/sys/unix/syscall_solaris.go:46: direntIno redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:1171
go/src/golang.org/x/sys/unix/syscall_solaris.go:50: direntReclen redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:1175
go/src/golang.org/x/sys/unix/syscall_solaris.go:54: direntNamlen redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:1179
go/src/golang.org/x/sys/unix/syscall_solaris.go:64: Pipe redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:96
go/src/golang.org/x/sys/unix/syscall_solaris.go:78: (*SockaddrInet4).sockaddr redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:363
go/src/golang.org/x/sys/unix/syscall_solaris.go:92: (*SockaddrInet6).sockaddr redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:377
go/src/golang.org/x/sys/unix/syscall_solaris.go:107: (*SockaddrUnix).sockaddr redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:392
go/src/golang.org/x/sys/unix/syscall_solaris.go:133: Getsockname redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:747
go/src/golang.org/x/sys/unix/syscall_solaris.go:142: ImplementsGetwd redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:232
go/src/golang.org/x/sys/unix/syscall_solaris.go:146: Getwd redeclared in this block
        previous declaration at go/src/golang.org/x/sys/unix/syscall_linux.go:236
go/src/golang.org/x/sys/unix/syscall_solaris.go:146: too many errors
# github.com/prometheus/client_golang/prometheus
go/src/github.com/prometheus/client_golang/prometheus/registry.go:400: syntax error: unexpected range, expecting {
go/src/github.com/prometheus/client_golang/prometheus/registry.go:514: non-declaration statement outside function body
go/src/github.com/prometheus/client_golang/prometheus/registry.go:515: non-declaration statement outside function body
go/src/github.com/prometheus/client_golang/prometheus/registry.go:516: syntax error: unexpected }
```

**Comment by petarkozic** [comment]
I had problem with this. Problem is in golang.

Remove any go and try to install from this link:

https://tecadmin.net/install-go-on-centos/




On October 31, 2017 at 10:20:18 AM, Ganesh Kaila (notifications@github.com)
wrote:

I am seeing the following errors in my environment. My apologies, I have
seen this error another machine which has Ubuntu 14.04, not Ubuntu 16.04.

biarca@prometheus-yes:~$ go version
go version go1.2.1 linux/amd64
biarca@prometheus-yes:~$ echo $GOPATH
/home/biarca/go
biarca@prometheus-yes:~$ go get github.com/neezgee/apache_exporter
# golang.org/x/sys/unix
go/src/golang.org/x/sys/unix/syscall_solaris.go:46
<http://golang.org/x/sys/unixgo/src/golang.org/x/sys/unix/syscall_solaris.go:46>:
direntIno redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:1171
go/src/golang.org/x/sys/unix/syscall_solaris.go:50
<http://golang.org/x/sys/unix/syscall_linux.go:1171go/src/golang.org/x/sys/unix/syscall_solaris.go:50>:
direntReclen redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:1175
go/src/golang.org/x/sys/unix/syscall_solaris.go:54
<http://golang.org/x/sys/unix/syscall_linux.go:1175go/src/golang.org/x/sys/unix/syscall_solaris.go:54>:
direntNamlen redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:1179
go/src/golang.org/x/sys/unix/syscall_solaris.go:64
<http://golang.org/x/sys/unix/syscall_linux.go:1179go/src/golang.org/x/sys/unix/syscall_solaris.go:64>:
Pipe redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:96
go/src/golang.org/x/sys/unix/syscall_solaris.go:78
<http://golang.org/x/sys/unix/syscall_linux_amd64.go:96go/src/golang.org/x/sys/unix/syscall_solaris.go:78>:
(*SockaddrInet4).sockaddr redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:363
go/src/golang.org/x/sys/unix/syscall_solaris.go:92
<http://golang.org/x/sys/unix/syscall_linux.go:363go/src/golang.org/x/sys/unix/syscall_solaris.go:92>:
(*SockaddrInet6).sockaddr redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:377
go/src/golang.org/x/sys/unix/syscall_solaris.go:107
<http://golang.org/x/sys/unix/syscall_linux.go:377go/src/golang.org/x/sys/unix/syscall_solaris.go:107>:
(*SockaddrUnix).sockaddr redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:392
go/src/golang.org/x/sys/unix/syscall_solaris.go:133
<http://golang.org/x/sys/unix/syscall_linux.go:392go/src/golang.org/x/sys/unix/syscall_solaris.go:133>:
Getsockname redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:747
go/src/golang.org/x/sys/unix/syscall_solaris.go:142
<http://golang.org/x/sys/unix/syscall_linux.go:747go/src/golang.org/x/sys/unix/syscall_solaris.go:142>:
ImplementsGetwd redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:232
go/src/golang.org/x/sys/unix/syscall_solaris.go:146
<http://golang.org/x/sys/unix/syscall_linux.go:232go/src/golang.org/x/sys/unix/syscall_solaris.go:146>:
Getwd redeclared in this block
        previous declaration at
go/src/golang.org/x/sys/unix/syscall_linux.go:236
go/src/golang.org/x/sys/unix/syscall_solaris.go:146
<http://golang.org/x/sys/unix/syscall_linux.go:236go/src/golang.org/x/sys/unix/syscall_solaris.go:146>:
too many errors
# github.com/prometheus/client_golang/prometheus
go/src/github.com/prometheus/client_golang/prometheus/registry.go:400
<http://github.com/prometheus/client_golang/prometheusgo/src/github.com/prometheus/client_golang/prometheus/registry.go:400>:
syntax error: unexpected range, expecting {
go/src/github.com/prometheus/client_golang/prometheus/registry.go:514:
non-declaration statement outside function body
go/src/github.com/prometheus/client_golang/prometheus/registry.go:515:
non-declaration statement outside function body
go/src/github.com/prometheus/client_golang/prometheus/registry.go:516:
syntax error: unexpected }

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lusitaniae/apache_exporter/issues/22#issuecomment-340704638>,
or mute the thread

**Comment by Lusitaniae** [comment]
Is this still an issue for anyone?

**Comment by Lusitaniae** [comment]
Will close unless someone comes up. 

Please try to reinstall latest Go as specified in the comment before mine.
