### ISSUE TITLE
CentOS 6.8 Requirement for ld-musl-x86_64.so.1

### ISSUE THREAD

**Issue by jcantu-usgs** [Lusitaniae/apache_exporter#25]
Hi,

I was able to build this just fine but when I attempt to run it on a CentOS 6.8 system, it fails to run because of a missing library ld-musl-x86_64.so.1.  I had to build this library from scratch and deploy it along with the apache_exporter using the code I found here:
https://www.musl-libc.org/download.html

Can you explain why this might be the case?  Strange that a Go app would require a C library.

**Comment by neezgee** [comment]
No, I cant :-)

Can you build, install and run other go packages?

**Comment by jcantu-usgs** [comment]
Yes I can.  In fact, we've deployed mongdb_exporter,
elasticsearch_exporter, and jmx_exporter.  All Go apps.  The
apache_exporter is the only one we've had to concern ourselves with this
particular issue.  We are deploying on Centos 6.9 (I know - it's old).  We
are building with the Docker alpine image, then packaging into an rpm using
the centos 6.9 docker image (since that's what we're deploying to).

I'm guessing that this issue is limited to the older CentOS platforms.


Jonathan

**Comment by jcantu-usgs** [comment]
Just realized that jmx_exporter is not, but the others are.  Since my last
response, we have also deployed postgres_exporter which also apparently
required ld-musl-x86_64.so.1.

Not sure why just those 2 exporters (thus far) have required this library
on Centos 6.9.

**Comment by Lusitaniae** [comment]
Is this still an issue for anyone?

**Comment by Lusitaniae** [comment]
For the releases we include some compile flags to ensure its static compiled.

https://github.com/Lusitaniae/apache_exporter/blob/master/.promu.yml#L4

Did you compile yourself earlier? Any specific flags you used?

**Comment by Lusitaniae** [comment]
Will close this issue for now.
