### ISSUE TITLE
Using "-insecure" parameter cause a 401 during scrape

### ISSUE THREAD

**Issue by jdvr** [Lusitaniae/apache_exporter#31]
While testing #29  I have discovered a weird issue, when running binary using `-insecure` as first argument. I get a 401 during the scrape, This are the outputs for the different tests:
```
./apache_exporter -insecure "false" -scrape_uri "http://prom:prom@localhost/server-status?auto"
```
```
INFO[0000] Starting apache_exporter (version=0.4.0, branch=HEAD, revision=7131d6b924ccd3919c366626eca19022a18da811)  source="apache_exporter.go:291"
INFO[0000] Build context (go=go1.9.1, user=root@612a33366ebc, date=20171007-10:55:46)  source="apache_exporter.go:292"
INFO[0000] Starting Server: :9117                        source="apache_exporter.go:294"
ERRO[0001] Error scraping apache: Status 401 Unauthorized (401): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at localhost Port 80</address>
</body></html>
  source="apache_exporter.go:273"
```
```
> ./apache_exporter -scrape_uri "http://prom:prom@localhost/server-status?auto"                  
```
```
INFO[0000] Starting apache_exporter (version=0.4.0, branch=HEAD, revision=7131d6b924ccd3919c366626eca19022a18da811)  source="apache_exporter.go:291"
INFO[0000] Build context (go=go1.9.1, user=root@612a33366ebc, date=20171007-10:55:46)  source="apache_exporter.go:292"
INFO[0000] Starting Server: :9117                        source="apache_exporter.go:294"
```
In each case, start the exporter and access to `http://localhost:9117/metrics`  in the browser.

The Apache configuration is copied from #29.
Does it make sense for you? I have also tried `-insecure false` and `-insecure true`, any combination result in the same problem.

It seems like the `-scrape_uri` is ignore when insecure is set.
I am using this binary https://github.com/Lusitaniae/apache_exporter/releases/download/v0.4.0/apache_exporter-0.4.0.linux-amd64.tar.gz

**Comment by Lusitaniae** [comment]
Seems to be related to the flag parsing. I've replicated your results, but
managed to get it working with:

./apache_exporter -insecure=false -scrape_uri=http://prom:prom@localhost
/server-status?auto

**Comment by Lusitaniae** [comment]
Its actually documented:

https://golang.org/pkg/flag/

Command line flag syntax:

-flag
-flag=x
-flag x  // non-boolean flags only

**Comment by jdvr** [comment]
Great, so this is not an issue but a wrong usage :-)

Thanks!
