### ISSUE TITLE
Collecting metrics from multiple containers

### ISSUE THREAD

**Issue by roshu10** [Lusitaniae/apache_exporter#32]
Hi,

How do we collect metrics from single box when multiple containers are running on it ?

For example: If 9 containers are running in 2 machines, Those 9 container will be using a random service ports selected by orchestration tool.

In that scenario, How do we collect Apache stats from those 2 boxes (machine-wise/aggregate reports).

Thanks for any help !!

**Comment by Lusitaniae** [comment]
Hi @roshu10 

The best practice for prometheus is to use one exporter for each process you wish to monitor.

If you have 9 apache instances running on 2 machines through docker, you should have another 9 instances of apache exporter along side them.

Most (if not all) exporters are made to work in this way.

**Comment by roshu10** [comment]
Thanks for your reply :) 

qtn1)
Is there any way to run one exporter per server to monitor multiple container ?

qtn2)
if 4 apache containers are running in one box, how can i run 4 exporters ?
4 apache containers will be having random service ports assigned by orchestration tool. I don't want to run 4 exporters manually every time apache container gets created.
How can we automate it ?

**Comment by Lusitaniae** [comment]
Hi,

You have to use the orchestrator tool to automate it. I can’t help much in
that but I’m sure you can google something.

One of the options required to run this exporter is the scrape url.
