### ISSUE TITLE
Error running through Docker

### ISSUE THREAD

**Issue by Preston1299** [Lusitaniae/apache_exporter#33]
when I use the command: "docker run -d -p 9117:9117 apache_exporter", all I get is this error: standard_init_linux.go:185 exec user process caused "exec format error.

This is my Dockerfile: 
FROM quay.io/prometheus/busybod:latest

COPY apache_exporter.go /bin/apache_exporter

ENTRYPOINT ["/bin/apache_exporter"]
EXPOSE          9117

**Comment by Lusitaniae** [comment]
I imagine the answer at https://github.com/prometheus/busybox/issues/11 solved your issue. Closing this issue.
