### ISSUE TITLE
Scrape server with self signed certificate

### ISSUE THREAD

**Issue by Preston1299** [Lusitaniae/apache_exporter#34]
Im unable to get apache status on a server running on a self signed certificate. Is there any way to skip this? Scraper seems to fail at this [point](https://github.com/Lusitaniae/apache_exporter/blob/f6a5b4814ea795ee9eac745c55649cce9e5117a9/apache_exporter.go#L286-L289)

```go
func (e *Exporter) Collect(ch chan<- prometheus.Metric) {
	e.mutex.Lock() // To protect metrics from concurrent collects.
	defer e.mutex.Unlock()
	if err := e.collect(ch); err != nil {
		log.Errorf("Error scraping apache: %s", err)
		e.scrapeFailures.Inc()
		e.scrapeFailures.Collect(ch)
	}
	return
}
```

Is there a way to skip SSL validation?

**Comment by Lusitaniae** [comment]
Hi @Preston1299 

Did you try the -insecure flag?

./apache_exporter -insecure=True  ?
