### ISSUE TITLE
Important metrics are missing

### ISSUE THREAD

**Issue by ping2nomula** [Lusitaniae/apache_exporter#35]
Hi There,

I have installed go package for this apache_exporter in my centos machine and also enabled the server-status for apache instance.

Apache server-status page is giving the required metric like "10 requests currently being processed, 90 idle workers"

Whereas apache_exporter page is missing to give any metric to find out how many requests are currently being processed and how many are being in idle state (Missing - apache_accesses_total ). 
![image](https://user-images.githubusercontent.com/19729764/34842557-b4b875fe-f6c0-11e7-8e66-5ed51ffdbcc6.png)
![image](https://user-images.githubusercontent.com/19729764/34842576-c2fe6cfe-f6c0-11e7-98f6-8f16e0f3c742.png)
![image](https://user-images.githubusercontent.com/19729764/34842588-ce3917a4-f6c0-11e7-93ec-7a280c64074a.png)

Request your help in this.

Thanks
Anka

**Comment by Lusitaniae** [comment]
hi @ping2nomula , whats the output of the apache_exporter?

From the screenshot it seems it didn't connect or parse the data correctly. Most of the metrics are related to the exporter process itself while Apache's are missing.

**Comment by ojle** [comment]
ReqPerSec is also missing. Can you include that?

**Comment by Lusitaniae** [comment]
Please share the output of running ./apache_exporter from the command line.

**Comment by ojle** [comment]
./apache_exporter -telemetry.address=":9100"
INFO[0000] Starting apache_exporter (version=0.5.0, branch=HEAD, revision=f6a5b4814ea795ee9eac745c55649cce9e5117a9)  source="apache_exporter.go:305"
INFO[0000] Build context (go=go1.9.2, user=root@0fdc4d8924f5, date=20171113-21:19:13)  source="apache_exporter.go:306"
INFO[0000] Starting Server: :9100                        source="apache_exporter.go:307"

**Comment by Lusitaniae** [comment]
Thanks for the details.

if you access /metrics do you get any additional output?

**Comment by ojle** [comment]
Yes, I get these apache metrics from /metrics:

apache_accesses_total
apache_cpuload
apache_scoreboard
apache_sent_kilobytes_total
apache_up
apache_uptime_seconds_total
apache_workers

So there is no ReqPerSec.

**Comment by Lusitaniae** [comment]
Ah ok, but that’s a separate issue.

In the scoreboard you get all the active requests, you can just add it up.
In any case better make a new ticket.

**Comment by ojle** [comment]
Well since that value is exporter directly via apache status, it's good to be included as is.
Ok, I'll open another ticket.

**Comment by Lusitaniae** [comment]
I though the issue on this ticket was

**Comment by javsalgar** [comment]
Same issue here. I only get this metrics:

```
# HELP apache_cpuload The current percentage CPU used by each worker and in total by all workers combined (*)
# TYPE apache_cpuload gauge
apache_cpuload 0
# HELP apache_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which apache_exporter was built.
# TYPE apache_exporter_build_info gauge
apache_exporter_build_info{branch="master",goversion="go1.10.3",revision="1cdcf2ec56008a934c800defbbd3b78747d9ba5b",version="0.5.0"} 1
# HELP apache_up Could the apache server be reached
# TYPE apache_up gauge
apache_up 1
```

I do not get any more Apache metrics:

```
time="2018-10-29T10:06:38Z" level=info msg="Starting apache_exporter (version=0.5.0, branch=master, revision=1cdcf2ec56008a934c800defbbd3b78747d9ba5b)" source="apache_exporter.go:305"
time="2018-10-29T10:06:38Z" level=info msg="Build context (go=go1.10.3, user=root@06d588af59d5, date=20180715-10:05:53)" source="apache_exporter.go:306"
time="2018-10-29T10:06:38Z" level=info msg="Starting Server: :9117" source="apache_exporter.go:307"
time="2018-10-29T10:06:46Z" level=error msg="Error scraping apache: Error scraping apache: Get http://status.localhost:80/server-status: dial tcp 127.0.0.1:80: connect: connection refused" source="apache_exporter.go:287"
time="2018-10-29T10:07:36Z" level=error msg="Error scraping apache: Error scraping apache: Get http://status.localhost:80/server-status: dial tcp 127.0.0.1:80: connect: connection refused" source="apache_exporter.go:287"
```

The connection refused error was at the beginning when, Apache was not ready yet. In the Apache logs I can see it is being accessed

```
10.244.0.1 - - [29/Oct/2018:10:16:03 +0000] "GET /index.php HTTP/1.1" 200 3885
127.0.0.1 - - [29/Oct/2018:10:16:06 +0000] "GET /server-status HTTP/1.1" 200 1633
127.0.0.1 - - [29/Oct/2018:10:16:08 +0000] "GET /server-status HTTP/1.1" 200 1641
10.244.0.1 - - [29/Oct/2018:10:16:13 +0000] "GET /index.php HTTP/1.1" 200 3883
127.0.0.1 - - [29/Oct/2018:10:16:16 +0000] "GET /server-status HTTP/1.1" 200 1633
127.0.0.1 - - [29/Oct/2018:10:16:18 +0000] "GET /server-status HTTP/1.1" 200 1642
10.244.0.1 - - [29/Oct/2018:10:16:23 +0000] "GET /index.php HTTP/1.1" 200 3882
127.0.0.1 - - [29/Oct/2018:10:16:26 +0000] "GET /server-status HTTP/1.1" 200 1632
127.0.0.1 - - [29/Oct/2018:10:16:28 +0000] "GET /server-status HTTP/1.1" 200 1637
```

As you can see, the date is after the error

**Comment by Lusitaniae** [comment]
hi @javsalgar 
What commands are you using?

How do I replicate what you're trying to do?

**Comment by javsalgar** [comment]
Just found the cause of the issue. I was missing the `?auto` at the end of the scrape uri. Sorry for the inconvienience

**Comment by Lusitaniae** [comment]
Glad to hear its solved
