### ISSUE TITLE
Add ReqPerSec metric

### ISSUE THREAD

**Issue by ojle** [Lusitaniae/apache_exporter#36]
If possible, add ReqPerSec metric which is directly exported via /server-status?auto

**Comment by roidelapluie** [comment]
We do not want to do so. You can just use Prometheus' rate () function to do so.

**Comment by ojle** [comment]
Why don't you get all data from /server-status?auto as is , instead of selecting just few ones, and making other possible by various prometheus functions?

**Comment by roidelapluie** [comment]
The real question is why do you want to fetch that data while you can just use the rate() function over the total of requests. We try to stay close to the prometheus philosophy where you expose counters, not gauges for that metric.

**Comment by Lusitaniae** [comment]
@ojle , the same issue was discussed here previously: https://github.com/Lusitaniae/apache_exporter/pull/27

Making the calculation in Prometheus gives you more flexibility.

You can calculate different rates (requests per second, 10 second, 30 second, etc) which will be useful if you're looking at graphs and search in different timelines (last 4h, 12h, last 3 days, last 7 days) and want to adjust granularity accordingly.

**Comment by ojle** [comment]
My point is, all metrics that are exposed from apache, should be gathered. (since those are 'official' metrics)
And later, it will be users decision, what metrics will use, 'default ones' or special prometheus functions

**Comment by roidelapluie** [comment]
We should not colject all metrics from apache (I do not see why bothering with that gauge).
(Also all the metrics we collect should be remaned to match prometheus best practices.)

**Comment by Lusitaniae** [comment]
ojle, we try to follow the standards set by prometheus and there's little
to no benefit in including this metric.
