### ISSUE TITLE
Allow "scrape_uri" to be passed via URL as target

### ISSUE THREAD

**Issue by schweikert** [Lusitaniae/apache_exporter#39]
It is a bit of a Prometheus anti-pattern to configure in the exporter itself what should be monitored. That configuration should be retrieved by Prometheus using service-discovery, and passed on to the exporter. A good example of this is the blackbox_exporter, which uses the "target" parameter to identify what service to probe.

So, I suggest that apache_exporter also implements a "target" parameter, and uses that instead of the default or what is given in --scrape_url, if defined.

This would also solve  #37, and simplify deployment (if server-status is accessible from a single host, you only need to deploy it once).

**Comment by schweikert** [comment]
I will try to write a patch for this :)

**Comment by Lusitaniae** [comment]
I wouldn't say is an anti pattern because one exporter does that, while every other one does not. 
If you have more examples would be interesting to hear about it. 

https://github.com/prometheus/haproxy_exporter/issues/65#issuecomment-251916058

You can see this comment here, grobie is using chef to setup Haproxy and the respective exporters and record the results in consul for service discovery.
Prometheus will then query consul to know what exporters to scrape.

Therefore, keeping the rule of one exporter per process being monitored.

**Comment by schweikert** [comment]
OK, maybe I shouldn't say "anti-pattern" (but note that the blackbox_exporter is written by Brian Bazil, so I would follow his lead for patterns...).

Anyway: I think that it can work both ways. If a target is specified, use that, otherwise take what is configured on the command-line (or the default).

**Comment by Lusitaniae** [comment]
If you read this page, the blackbox and snmp exporter are particularly _singled out as being exceptions_ to one process one exporter rule: https://prometheus.io/docs/instrumenting/writing_exporters/.

> There are two exceptions:
> 
> The first is where running beside the application your monitoring is completely nonsensical. The SNMP, blackbox and IPMI exporters are the main examples of this. 


> . For exporters such as the blackbox exporter and SMNP exporter, which aren’t tied to a single target, these should only be exposed on a vanilla /metrics call, not on a scrape of a particular target.


Allowing prometheus to scrape multiple targets from a single exporter would be the anti-pattern.

I think its not worthwhile to come up with a patch. I try to keep the exporter as closely as possible to the official exporters, and the ones more closely related to Apache exporter don't support that option.

**Comment by schweikert** [comment]
OK, I won't spend time in creating a pull request. Personally I still think that it would be a small change with no big maintenance burden that could be useful to some users.
