### ISSUE TITLE
CentOS 7.4 can't load package

### ISSUE THREAD

**Issue by Terramoto** [Lusitaniae/apache_exporter#41]
# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/src/github.com/apache_exporter/"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build597971533=/tmp/go-build -gno-record-gcc-switches"
[root@osboxes apache_exporter]# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/src/github.com/apache_exporter/"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build442579677=/tmp/go-build -gno-record-gcc-switches"

# echo $GOPATH
/src/github.com/apache_exporter
# echo $GOROOT
/usr/local/go

# echo $PATH
:/usr/local/go/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/osboxes/.local/bin:/home/osboxes/bin:/usr/local/go/bin

# go list | grep -v /vendors/
_/src/github.com/apache_exporter

# make
>> formatting code
can't load package: package _/src/github.com/apache_exporter: cannot find package "_/src/github.com/apache_exporter" in any of:
	/usr/local/go/src/_/src/github.com/apache_exporter (from $GOROOT)
	/src/github.com/apache_exporter/src/_/src/github.com/apache_exporter (from $GOPATH)
make: *** [format] Error 1

Sorry to waste your time, but i'm not sure what's causing this. It seems like the '_' is being added to the path causing it to fail but i'm not familiar with go or apache_exporter.

**Comment by Lusitaniae** [comment]
Seems you're missing the username from the path.
src/github.com/Lusitaniae/apache_exporter

**Comment by Terramoto** [comment]
all the variables are set to /src/github.com/apache_exporter where the folder is located as well. Would the path be setup on the source code for src/github.com/Lusitaniae/apache_exporter ?

**Comment by Lusitaniae** [comment]
Hi @Terramoto 
With Golang you usually set a GOPATH common to all your projects. Doing that solves your problem.

```
$ echo $GOPATH
/home/y/go

$ mkdir /tmp/go


$ export GOPATH=/tmp/go

$ cd /tmp/go

$ go get -u github.com/Lusitaniae/apache_exporter


$ ll src/github.com/Lusitaniae/apache_exporter/
total 60
drwxrwxr-x 4 y y 4096 May  3 21:26 ./
drwxrwxr-x 3 y y 4096 May  3 21:26 ../
-rw-rw-r-- 1 y y 7903 May  3 21:26 apache_exporter.go
-rw-rw-r-- 1 y y 3447 May  3 21:26 apache_exporter_test.go
-rw-rw-r-- 1 y y 2401 May  3 21:26 circle.yml
-rw-rw-r-- 1 y y  135 May  3 21:26 Dockerfile
drwxrwxr-x 8 y y 4096 May  3 21:26 .git/
-rw-rw-r-- 1 y y 1075 May  3 21:26 LICENSE
-rw-rw-r-- 1 y y 1735 May  3 21:26 Makefile
-rw-rw-r-- 1 y y  616 May  3 21:26 .promu.yml
-rw-rw-r-- 1 y y 4215 May  3 21:26 README.md
drwxrwxr-x 5 y y 4096 May  3 21:26 vendor/
-rw-rw-r-- 1 y y    6 May  3 21:26 VERSION

$ cd src/github.com/Lusitaniae/apache_exporter/

$ make
>> formatting code
>> building binaries
 >   apache_exporter
>> running tests
ok  	github.com/Lusitaniae/apache_exporter	0.008s

```

**Comment by Lusitaniae** [comment]
Closing if there's no open issue anymore.
