### ISSUE TITLE
grafana dashboard or collectd-compatible metrics

### ISSUE THREAD

**Issue by drzraf** [Lusitaniae/apache_exporter#46]
Is there an existing Grafana dashboard compatible with this exporter's metrics?
If not, I believe the way to go is to try to match collectd plugin metrics export to avoid dashboard fragmentation: https://grafana.com/dashboards?search=apache

**Comment by drzraf** [comment]
Does not work for me: no graph data for the node (although available and selected in the dashboard).

Maybe related to the fact that my target is an IPv6 (I can see that, contrary to node-exporter, the target's IP in grafana dashboard target `<select>` shows only the first 4 bytes of the IPv6, but I don't know on which side the bug lays).
[but issue is maybe unrelated]

In any case I also additionally have a `parse error at char 13: unknown function with name \"count_scalar\""` specific to Apache "up/down status" (@rfrail3 ?)

**Comment by vuzzlevuzz** [comment]
https://grafana.com/dashboards/3894 - works for me

I got the same "count_scalar" error but if you just edit the panel and hide that query it works fine

Re IPv6 - I am using ipv4 but with hostnames for the targets and not having any problems.  You may need to change the regex for the variables in the panel if it is truncating IPv6 addresses

**Comment by Lusitaniae** [comment]
Issue has been addressed and merged on their repo, see https://github.com/rfrail3/grafana-dashboards/issues/25 

I think we can close this issue. 

The dashboard works, possible issues may be better discussed on the author's repo https://github.com/rfrail3/grafana-dashboards
