### ISSUE TITLE
mod proxy status export

### ISSUE THREAD

**Issue by drzraf** [Lusitaniae/apache_exporter#47]
mod-proxy hooks in mod-status to provide additional metrics of interest.
Would be nice if those could be parsed and exported too.

**Comment by drzraf** [comment]
I don't have the time to do it.
`mod_proxy` lines for `mod_status` in `?auto` mode (= `AP_STATUS_SHORT`) are generated [here](https://github.com/apache/httpd/blob/2.4.x/modules/proxy/mod_proxy.c#L2842), they start with ProxyBalancer

**Comment by rainerjung** [comment]
See PR #102

**Comment by Lusitaniae** [comment]
Merged #102
