### ISSUE TITLE
Multi-Stage Dockerfile

### ISSUE THREAD

**Issue by Drc0w** [Lusitaniae/apache_exporter#49]
Hey there!

I recently used `apache_exporter` in a virtual instance which does not have Go environment. I was unable to build the binary by myself and had to use a docker container with the Go environment, build the app and then build the final image.

In the README, it is specified that the image has to be built from the Dockerfile, but it seems that beforehand the binary has to be already generated.

In this case it may be interesting to have a multi-stage Dockerfile that will handle the compilation part with Go environment and then the busybox part that would retrieve the binary file.

**Comment by Lusitaniae** [comment]
Hi Henry,

Currently I’m using CircleCI to build the go binary and package it in a
docker container.

That’s why the docker file is simply using the generated file to build a
new image.

In any case, you can go to this project, “releases” and find the pre
compiled packages.

https://github.com/Lusitaniae/apache_exporter/releases
