### ISSUE TITLE
How to get target as a element?

### ISSUE THREAD

**Issue by gcavalcante8808** [Lusitaniae/apache_exporter#50]
I'm using grafana to plot some graphs with the exporter information, but the data inserted into prometheus doesn't have "target" as an element and I want to have these as value in grafana. Is it possible? 

If so, can you provide an sample of prometheus.yml for that?

Thanks in advance.

**Comment by Lusitaniae** [comment]
hi @gcavalcante8808 ,

Have a look at my other exporter, I have some demo grafana dashboards there.

https://github.com/Lusitaniae/phpfpm_exporter/blob/master/contrib/php-fpm.json#L120

You can see that targets are expression/queries to the data prometheus contains.

**Comment by Lusitaniae** [comment]
Closing unless you have additional questions.
