### ISSUE TITLE
Count_scalar removed in Prometheus 1.8.2

### ISSUE THREAD

**Issue by RicardoJeronimo** [Lusitaniae/apache_exporter#52]
Hey!

I started using Prometheus with Grafana recently and one of the graphs is giving this error:
`parse error at char 13: unknown function with name "count_scalar" `

Aparently, count_scalar() was replaced with scalar(count()): https://github.com/grafana/grafana-plugins/issues/45

**Comment by Lusitaniae** [comment]
hi @RicardoJeronimo 

We can close in that case right?

Problem is solved in the dashboard queries to Prometheus.
