### ISSUE TITLE
Apache_up shows 0 even my apache_exporter is on

### ISSUE THREAD

**Issue by janeunbi** [Lusitaniae/apache_exporter#53]
When I type my apache_exporter on URL, I can see it is ON right now.
![1](https://user-images.githubusercontent.com/46011780/50669125-b5f39b00-1006-11e9-9816-b234adb9f7bf.PNG)

HOWEVER, I try to figure its graph out, it tells apache_up is 0.
![2](https://user-images.githubusercontent.com/46011780/50669231-547ffc00-1007-11e9-9d57-652f86d0cac0.PNG)

Even though I can access my web server and it works normally. 

What should I do to solve this problem?

**Comment by Lusitaniae** [comment]
hi,

You can click on "Metrics" to see all the data.

http://58.229.253.182:9117/metrics

**Comment by janeunbi** [comment]
hi @Lusitaniae 
Thank you for your reply 
nope it doesn't work, I can see the all metrics provided.
I can't understand why value of apache_up comes out 0 even the apache_exporter and apache still working on.

**Comment by janeunbi** [comment]
Here's my all the Apache metrics and apache_up status behind the chart.
![all](https://user-images.githubusercontent.com/46011780/50802887-940e5700-132b-11e9-8734-c9302b2265e0.png)
Through this, I can figure it out its metrics works except apache_up metric

**Comment by Lusitaniae** [comment]
Look at the read me, there’s more metrics than that, can you check the
other things I asked above?

**Comment by Lusitaniae** [comment]
the command is meant to retrieve the status page from Apache itself, so running it in the same machine as apache is the right one.

Looking at that 301 redirect you show on the 2nd screenshot I'd say the rewrite rule you use to enforce https is not working as expected, as you can see there's a slash missing there.

**Comment by janeunbi** [comment]
Thank you for trying to help me.
I read your comment over and over, not sure I'm in the right direction.
1. which one is 301 redirect?
2. you mean "https" causing this problem, am I right?
3. To fix this problem, I need to enable Apache Server Status Page and should make or edit configuration file in the Web server. 
p.s. I'm not sure I understand what you said. Unfortunately, web server is belong to my work, I don't think I able to fix that file.

**Comment by Lusitaniae** [comment]
@janeunbi, maybe its possible someone else at your company have a look at this?

If the Apache config needs to be fixed to make it work, there's no other way around it.

**Comment by Lusitaniae** [comment]
hi @janeunbi 

Is this still an issue?

Is there anything I can help with?

**Comment by Lusitaniae** [comment]
I will close the issue unless you need additional feedback here.

In case you dive into this further, the answer to your questions

1. the redirect is seen on the 2nd screenshot you've sent
2. Can be, there's a redirect rule somewhere that is causing the missing slash-
3. yes, you need to review the web server config.
