### ISSUE TITLE
Collecting metrics from multiple targets (à la blackbox_exporter)

### ISSUE THREAD

**Issue by dmke** [Lusitaniae/apache_exporter#54]
Hi,

I'd like to do something like the [blackbox_exporter](https://github.com/prometheus/blackbox_exporter) does: collecting metrics from multiple Apache instances, and parameterize the actual target with the query.

Example: scraping `http://localhost:9117/metrics?target=http%3A%2F%2Fexample.com/server-status%2F%3Fauto` should be equivalent (*) to `apache_exporter -scrape_url 'http://example.com/server-status/?auto'`, but with the extended functionality of making the `target` parameter... well, parameterizable.

(*) modulo the relabeling required

This has the huge advantage of deploying only one `apache_exporter` instance (and not one alongside each Apache server/container). It basically resolves #32.

The modifications necessary for this are manageable:

```diff
@@ var ( @@
+	targetsEndpoint  = flag.String("telemetry.targets", "/probe", "Path under which to expose dynamic metrics.")

@@ func main() { @@
+	http.HandleFunc(*targetsEndpoint, func(w http.ResponseWriter, r *http.Request) {
+		target := r.FormValue("target")
+		if target == "" {
+			http.Error(w, "bad request: missing target parameter", http.StatusBadRequest)
+			return
+		}
+		reg := prometheus.NewRegistry()
+		exporter := NewExporter(target)
+		reg.MustRegister(exporter)
+		h := promhttp.HandlerFor(reg, promhttp.HandlerOpts{})
+		h.ServeHTTP(w, r)
+	})
```

Eventually (after polishing and testing), I'd like to open a PR. However, it makes the `-scrape_url` superflous, and the `/metric` endpoint (mostly) useless, so I'm asking for guidance. Do you think you'd merge a pull request with these changes, or do you think this would be better a seperate exporter altogether?

**Comment by Lusitaniae** [comment]
hi @dmke 

#32 was closed since it doesn't follow Prometheus best practices. 

This is going in the same direction.

I suggest you fork this repo and change as required if you feel so inclined to follow in that direction.

**Comment by dmke** [comment]
I see, thank you for your time.

**Comment by Lusitaniae** [comment]
Thank you!

**Comment by henri9813** [comment]
Hello @dmke ,

Did you published this somewhere ?

I'm interested by your feature :D 

Best regards,

**Comment by dmke** [comment]
@henri9813: No, we've moved away from Apache and don't need the exporter anymore.
