### ISSUE TITLE
support for Host header

### ISSUE THREAD

**Issue by ketzacoatl** [Lusitaniae/apache_exporter#57]
some Apache deployments require using a Host header when accessing the status page. It would be great if `apache_exporter` were able to support this. I've reviewed the code, it is simple, and this ought to be an easy task, though I was not 100% sure how to specify this when using the http client. I attempted to pipe in that header when making the request to apache, but I have not spent enough time with golang to be very effective.

The context is running multiple instances of apache, where each instance of apache has its own `apache_exporter` scrapping `mod_status`. `apache_exporter` refers to each instance by IP port directly, rather than going through a load balancer or other routing layers.

**Comment by roidelapluie** [comment]
just put the host in the status url.

http://myhost/

**Comment by ketzacoatl** [comment]
That would work if you ran 1 instance of apache. Let's say you have multiple instances of apache running, so you then run one instance of `apache_exporter` per instance of apache. Each `apache_exporter` is going to talk to exactly one instance of apache on a particular `http://IP:port`. The instances get tagged, and you want continuity in the metrics and where they originate from. You do not want it moving around. This is why we point `apache_exporter` at an IP:port, and then end up needing to include the `Host` header for applications that rely on that for routing through the vhost configuration.

**Comment by Lusitaniae** [comment]
@ketzacoatl if you use the host in the status url it will resolve the hostname to the local instance or is that not gonna work for you?

**Comment by ketzacoatl** [comment]
When reviewing the HTTP client code, it seems easy to make a spot for the host header, but I'm not 100% sure I see how to do this correctly in the `apache_exporter` code base. Can anyone point me in the right direction to poke at this some more? Thanks :)

**Comment by Lusitaniae** [comment]
hi @ketzacoatl , have a look at 

https://github.com/Lusitaniae/apache_exporter/blob/master/apache_exporter.go#L168

**Comment by ketzacoatl** [comment]
Thanks for the info @Lusitaniae! I've got zero significant golang experience, but I'll see what I can work out :)

**Comment by Lusitaniae** [comment]
Merged PR should solve it.

**Comment by ketzacoatl** [comment]
yahoo! thanks!
