### ISSUE TITLE
server-status lost Metrics

### ISSUE THREAD

**Issue by wumt** [Lusitaniae/apache_exporter#61]
![图片](https://user-images.githubusercontent.com/25841370/56630196-22aca700-6683-11e9-9ec4-38ccc7abfbae.png)

in my Apache server-status  we found lost some Metrics

Server Version: Apache/2.2.22 (Unix) mod_ssl/2.2.22 OpenSSL/1.0.0g mod_cluster/1.2.9.Final

**Comment by wumt** [comment]
i only found this 
![图片](https://user-images.githubusercontent.com/25841370/56642059-3bc84e80-66a9-11e9-941e-af052b8d1409.png)

**Comment by wumt** [comment]
just like #35

**Comment by wumt** [comment]
lost
apache_accesses_total
apache_uptime_seconds_total
apache_sent_kilobytes_total
apache_cpuload

**Comment by Lusitaniae** [comment]
hi @wumt 

Can you show how you're running the exporter in the command line?

**Comment by wumt** [comment]
sorry i did not add 
`ExtendedStatus On`
in my httpd.conf 

Thank you all the same

**Comment by Lusitaniae** [comment]
No problem
