### ISSUE TITLE
grafana dashboard

### ISSUE THREAD

**Issue by walkmans0401** [Lusitaniae/apache_exporter#63]
hi ~

i used apache_exporter 0.6 , but i use grafana dashboard 3894

this dashboard only apache_up/down working 

and other all show "no data potins"

it what happend ? or i need down to use apache expoeter 0.5 ?

![Image 4](https://user-images.githubusercontent.com/10649659/58396010-5b261300-807d-11e9-9610-05080f983448.png)

**Comment by Lusitaniae** [comment]
hi @walkmans0401 

Last time I tested, the mentioned dashboard seemed to work with this exporter.  However I haven't been actively using Prometheus for a while, so I don't keep up with everything. 

There should be no breaking changes between both exporter versions.

Can you check:

1. What metrics the apache exporter is providing you.

and compare with

2. What metrics are being queried in the graphs.

Thanks,
Pedro
