### ISSUE TITLE
Under load apache doesn't return stats, and then your don't get metrics

### ISSUE THREAD

**Issue by DTTerastar** [Lusitaniae/apache_exporter#75]
Seems like a design flaw.  I'd like to use this metrics to scale apache, but if I get hit hard I get absolutely nothing but scrape fails.

**Comment by Lusitaniae** [comment]
Not sure we can do anything about that

Maybe increase timeout?

But Prometheus scrapes every 10 seconds by default so you should be able to
see the moment leading to it

If you get scrape failure is also a sign you should scale anyway, right?

Can look further into it later on

**Comment by Lusitaniae** [comment]
Closing if there's no further updates.
