### ISSUE TITLE
http_* metrics missing from Apache Exporter 0.7.0

### ISSUE THREAD

**Issue by ayoya179** [Lusitaniae/apache_exporter#77]
All http_* metrics do not get shown in apache exporter version 0.7.0 ... Only until version 0.5.0 are they still shown.
Since the documentation mentions them, customers keep complaining why they can not be viewed.

**Comment by Lusitaniae** [comment]
Metrics have been removed from the documentation in the linked PR.

These metrics originate from the prometheus libraries regarding the exporter activity and should not be required for end users.
