### ISSUE TITLE
Error in scraping apache: 404 Not Found

### ISSUE THREAD

**Issue by sbhatt692** [Lusitaniae/apache_exporter#80]
Hi,
I am running the exporter in a Linux server with apache running as a service. The exporter is returning 404 Not Found while it is scraping the apache. I have the same configuration running in other similar servers and it works fine.
The error message is listed below:
level=error msg="Error scraping apache: Status 404 Not Found... The requested URL was not found on the server. Please check the spelling of you entered it manually" source="apache_exporter.go:295"

**Comment by Lusitaniae** [comment]
hi @sbhatt692 

Still having the issue? Are you sure you have the same config?

Please provide more details.

What config do you have working, what config doesn't.

What release are you running

What parameters are you using
