### ISSUE TITLE
About apache_accesses_total

### ISSUE THREAD

**Issue by negi700** [Lusitaniae/apache_exporter#81]
Can I check the number of individual connections for the VirtualHost URL?
Could you tell me how to do it?

Thank you.

**Comment by Lusitaniae** [comment]
I think you'd need to use https://github.com/google/mtail to tail the logs and create metrics from it.

You can see some example config here:

https://github.com/google/mtail/tree/master/examples

**Comment by Lusitaniae** [comment]
If there's no more questions, gonna close this one.
