### ISSUE TITLE
Can we monitor apache tomcat 9 using this exporter ?

### ISSUE THREAD

**Issue by khadar-sk** [Lusitaniae/apache_exporter#82]
Can we monitor apache tomcat 9 using this exporter? If we can monitor can you provide the details of how to monitor?

I tried whatever there in the README.MD file. For httpd it is working fine, but I need to monitor the Tomcat application.

I am using centos 7
webserver httpd
application server Apache Tomcat

In httpd we have http://url/server-status
whereas  in  apache tomcat application we have http://url/manager/status/all  where we get all parameters of server status 

I tried 
`./apache_exporter -scrape_uri="http://tomcat:tomcat@10.95.126.205:8080/manager/status/all/`

The exporter is showing apache_up 1, but I am not able to get the metrics 

Thanks in Advance

**Comment by Lusitaniae** [comment]
Tomcat is a different project hosted by the Apache foundation.

You should use its own exporter, such as https://github.com/nlighten/tomcat_exporter

**Comment by khadar-sk** [comment]
Thank you very much for your reply. I thought that we can monitor the apache tomcat also. Now I got it
