### ISSUE TITLE
[Feature request] Expose metrics for `configtest` results

### ISSUE THREAD

**Issue by cryptobioz** [Lusitaniae/apache_exporter#85]
As the Apache server configuration can be changed and reloaded on live, it could be useful to expose some metrics to monitor this.

By running an `apachectl configtest` command every time the exporter is scraped, we could expose the following metrics:

- `apache_configtest_last_check_successful` will return `0` if the configuration is invalid and `1` if everything is okay.

- `apache_configtest_last_check_success_timestamp_seconds` will return the timestamp in seconds of the last time the check was successful.

These metrics might help us to prevent an Apache server to reload a faulty configuration or alert us before it happens.

I'll start writing a Pull Request to implement this. I'm open to suggestions and comments.

**Comment by roidelapluie** [comment]
Thanks for creating a request.

I am not sure I want this because configtest is an expensive and slow operation.

**Comment by cryptobioz** [comment]
Indeed, the other solution would be to run the configtest regularly instead running it at every request.

**Comment by mcanevet** [comment]
We tested it with a quite big configuration, and it took a few tens of milliseconds.
Maybe an opt-in parameter would be acceptable?

**Comment by roidelapluie** [comment]
an opt-in flag seems reasonable

**Comment by cryptobioz** [comment]
Well, we're facing a design problem. The exporter can, and it's a good thing, be used remotely. It doesn't depend on anything and only rely on the HTTP endpoint provided by Apache. It can be deployed next to Apache or on an other container or even on an other machine.

If we add the feature to expose the `configtest` result, we add an important dependency in this exporter. It will have to be deployed next to Apache in order to work properly because it will need access to the configuration files and the `apachectl` binary.

Therefore, I'm not sure it's a good thing to add this feature because it will begin to change the design of this exporter...

**Comment by Lusitaniae** [comment]
Not sure it's a big issue if it's disabled by default and people can enable
it as needed.

**Comment by roidelapluie** [comment]
I do think that it is an issue that would be better covered by node_exporter file collector

**Comment by cryptobioz** [comment]
When you talk about "node_exporter file collector", do you mean the textfile collector?

**Comment by roidelapluie** [comment]
Yes, calling external commands from the exporter exposes it to a new range of security threats.

**Comment by roidelapluie** [comment]
Also it has serious limitations like you should run the exporter with the same user as apache and use apache default path for configuration

**Comment by cryptobioz** [comment]
Indeed, I'm not a big fan of this solution too but I'd prefer to have a kind of _real_ exporter instead a cronjob. However, you're totally right regarding the security issues and limitations that this kind of workflow involves so I think your solution is the best.

**Comment by roidelapluie** [comment]
In general, configtest is run by e.g. config management before putting the new file in place, so it looks like the process to modify the file should run the configtest too and rollback wrong configs..

**Comment by cryptobioz** [comment]
Yeah, of course. But in our case, developers have the ability to modify the configuration files so they might break something and we would like to be informed as soon as possible. We will both agree to say that this is not a good practice but we don't have choice here.

**Comment by roidelapluie** [comment]
Please note that they can break the configuration in other ways that would not be caugh by this (e.g. removing vhosts). So that would anyway not be a complete solution for you.
