### ISSUE TITLE
Hard Dependency on Service

### ISSUE THREAD

**Issue by ankykong** [Lusitaniae/apache_exporter#88]
The apache_exporter has a hard dependency on the apache service, so if the service goes down, the apache_exporter goes down. I don't think that is optimal as it is inconvenient to have to restart the exporter every time the service goes down. Please let me know if there are any fixes. Thanks!

**Comment by Lusitaniae** [comment]
Sorry for the late response

I'm not currently using Apache exporter so difficult for me to review this

Either way, you should have systemd/init system to manage processes for you and auto restart as needed https://ma.ttias.be/auto-restart-crashed-service-systemd/
