### ISSUE TITLE
add apache_info metric with apache version

### ISSUE THREAD

**Issue by finkr** [Lusitaniae/apache_exporter#89]
Exposing Apache version to Prometheus would be nice as it allow to monitor migration and impacts.

See https://www.robustperception.io/exposing-the-software-version-to-prometheus

The ` server-status` report versions, like those exemples (gathered on the Internet)

> ServerVersion: Apache/2.4.37 (Red Hat) (Release 33.jbcs.el7-GA) OpenSSL/1.1.1 mod_cluster/1.3.12.Final-9
> ServerVersion: Apache/2.4.16 (Unix) OpenSSL/1.0.2h
> ServerVersion: Apache/2.4.23 (CentOS) OpenSSL/1.0.1e-fips
> ServerVersion: Apache/2.4.41 (Unix)
> ServerVersion: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1
> ServerVersion: Apache/2.2.22.2 (Unix) vFabric/5.1.1 vFabricLicense/5.1.1 mod_ssl/2.2.22.2 OpenSSL/1.0.1c-fips DAV/2
> ServerVersion: Apache/2.4.27 (Amazon) PHP/5.6.31 

A metric like this would be nice:

    apache_info{ version="2.4.37" }

The Apache source code generating the server-status is [mod_status.c](https://svn.apache.org/viewvc/httpd/httpd/trunk/modules/generators/mod_status.c?view=markup)

**Comment by roidelapluie** [comment]
apache_info{ version="2.4.37" }
 That would not be correct. We would need the full string. The reason is that "ServerVersion: Apache/2.4.23 (CentOS) OpenSSL/1.0.1e-fips" is not apache 2.4.23 but apache 2.4.23 with plenty of red hat patches.

**Comment by finkr** [comment]
This [feature](https://github.com/Lusitaniae/apache_exporter/pull/79) was merged in [v0.8.0 release](https://github.com/Lusitaniae/apache_exporter/releases)
Sorry for the noise.
