### ISSUE TITLE
Missing metrics in 0.8.0

### ISSUE THREAD

**Issue by waardd** [Lusitaniae/apache_exporter#90]
If i use the new 0.8.0 version of this exporter, i'm missing the new metrics....

# HELP apache_version Apache server version
# TYPE apache_version gauge
# HELP apache_duration_total Total duration of all registered requests
# TYPE apache_duration_total gauge

What can this be?

**Comment by Lusitaniae** [comment]
hi @waardd 

Could you please provide more details when creating issues?

Also check the FAQ for common issues

Since this is old issue and haven't heard back from you I will close it for now, let me know if you're still facing issues
