### ISSUE TITLE
unknown short flag '-s'

### ISSUE THREAD

**Issue by MagnusEnger** [Lusitaniae/apache_exporter#93]
Sorry if this has been reported before. When I try to do this:

`$ sudo service apache_exporter start`

I get this:

`nov. 18 09:58:28 myserver apache_exporter[7681]: apache_exporter: error: unknown short flag '-s', try --help`

The problem seems to be that /etc/systemd/system/apache_exporter.service has a single dash before `scrape_uri`:

```
# Ansible managed

[Unit]
Description=Prometheus Apache Exporter
After=local-fs.target network-online.target network.target
Wants=local-fs.target network-online.target network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/apache_exporter/apache_exporter -scrape_uri http://localhost/server-status/?auto

[Install]
WantedBy=multi-user.target
```

Changing `-scrape_uri` to `--scrape_uri` makes it possible to start the service again,

**Comment by rainerjung** [comment]
Version 0.8 changed the library used to handle commandline flags. All flags changed from single dash to double dash.
The repos here does not provide systemd files (or /etc/default files). They are typically added by the people maintaining a linux distro specific package. It would be best to find out the package maintainer for the apache_exporter provided by your distribution and contact her or him. There's probably nothing the project here can do about it now that the flag syntax change is out in the wild.

**Comment by Lusitaniae** [comment]
as mentioned by @rainerjung, an issue to discuss with package maintainer.
