### ISSUE TITLE
Correction in the documentation

### ISSUE THREAD

**Issue by ivanarsenijevic** [Lusitaniae/apache_exporter#99]
Hello,

The README.MD file states the following in the Run chapter:
```
docker run -d -p 9117:9117 apache_exporter \
  --scrape_uri="https://your.server.com/server-status/?auto"
```
The URI is incorrect, it should be without extra backslash: ``/server-status?auto``

This is just a detail but it caused me to spend too much time figuring out why the apache-exporter does not show all metrics it is supposed to :-)

Thanks,
Ivan

**Comment by Lusitaniae** [comment]
please have a quick look :) https://github.com/Lusitaniae/apache_exporter/pull/100/files

**Comment by Lusitaniae** [comment]
@rainerjung I will merge it, thank you
